name: Content Processor Agent CI

on: [push, pull_request]

jobs:
  test-and-lint:
    name: Test and Lint on Linux
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest (if tests exist)
      run: |
        pip install pytest
        # Check if test files exist, if not, skip testing
        if find . -name "test_*.py" -o -name "*_test.py" -o -path "*/tests/*" | grep -q .; then
          echo "Test files found, running pytest..."
          pytest
        else
          echo "No test files found, skipping tests..."
          echo "To add tests, create files matching: test_*.py, *_test.py, or put them in a 'tests' directory"
        fi